version: "3"
services:
  tadgan:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    tty: true
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./src
        target: /app/src/
    